#
# Common settings for new Emulab ports.
# This version will probably only work with version 9 (FreeBSD 13) and above.
#

.if !defined(EMULAB_PORTVERSION)

OSMAJOR!= /usr/bin/uname -r | /usr/bin/sed -e 's/\..*//'
OSMINOR!= /usr/bin/uname -r | /usr/bin/sed -e 's/[0-9][0-9]*\.\([0-9][0-9]*\).*/\1/'
OSARCH != /usr/bin/uname -m

EMULAB_PORTVERSION=	UNSUPPORTED

.if ${OSMAJOR} < 13
.error "only support FBSD 13 or higher"
.endif

.if ${OSMAJOR} > 13
.error "only support FBSD 13"
.else
.  if ${OSMINOR} < 5
EMULAB_PORTVERSION=	9.3
.  else
EMULAB_PORTVERSION=	9.5
.  endif
.endif
.endif

#
# Select PHP and Apache versions
# Fix up some port diffs
#
PHP_MAJ=5
PHP_VER=56
PY_VER=2.7
.if (${EMULAB_PORTVERSION} == "9.3")
# Note that mysql is really mariadb
PY_VER=3.9
DEFAULT_VERSIONS= perl5=5.36 python=3.9 python3=3.9 tcltk=8.6 php=8.1 mysql=10.6m apache=2.4
APACHE_PORT=www/apache24
APACHEMODDIR=libexec/apache24
MYSQL_VER=106
SWIG_VER=
SWIG_PORT=devel/swig
PHP_MAJ=8
PHP_VER=81
.else
.  if (${EMULAB_PORTVERSION} == "9.5")
# Note that mysql is really mariadb
PY_VER=3.11
DEFAULT_VERSIONS= perl5=5.36 python=3.11 python3=3.11 tcltk=8.6 php=8.1 mysql=10.6m apache=2.4
APACHE_PORT=www/apache24
APACHEMODDIR=libexec/apache24
MYSQL_VER=106
SWIG_VER=
SWIG_PORT=devel/swig
PHP_MAJ=8
PHP_VER=81
.  endif
.endif
