
# Second, foreach pkg and item INSTALLFILES-$(pkg), turn that into a full RPM
# package filename.  We do this by using spectool to get the version and 
# release from the spec file; grep'ing for noarch in the RPMBUILDFLAGS-$(pkg)
# and using that for arch, or i686 if x86, else uname -m; and using
# $(MYBUILDROOT) to make a full pathname.

all: $(addprefix built-,$(PKGS))

.SECONDEXPANSION:

# just sign them all for now...
sign: 
	sudo ./sign.pl `find RPMS | grep \.rpm\$$ | xargs` \
		`find SRPMS | grep \.rpm\$$ | xargs`

buildsource: $(addprefix buildsource-,$(PKGS)) $(foreach pkg,$(PKGS),$(addprefix buildsource-,$(LOCALBUILDPKGS-$(pkg))))

buildsource-%: $(SPECDIR)/$$*.spec source-$$*
	rpmbuild -bs $<

#
# extra layer of indirection so that the config variables can just use 
# 'installed-tcl' or similar, not INSTALLEDDIR/tcl
#
# NOTE: the prereq for this rule is commented out specifically!
# gnu make does not seem to support the implicit rule recursion we need, so
# we do our own!
#
installed-%: #$(INSTALLEDDIR)/$$*
	@if [ ! -e $(INSTALLEDDIR)/$* ]; then \
		echo "Doing our own recursion for target installed-$*!" ; \
		make -f $(firstword $(MAKEFILE_LIST)) $(INSTALLEDDIR)/$* ; \
	fi

$(INSTALLEDDIR)/%: install-$$*
	

install-%: built-$$*
	@if [ -z "$(INSTALLOPTS-$*)" ]; then \
		echo "Installing $* with default installopts!" ; \
		echo "  $(call find-built-pkg-filenames,$*)" ; \
		sudo rpm $(INSTALLOPTS-DEFAULT) $(call find-built-pkg-filenames,$*) ; \
	else \
		sudo rpm $(INSTALLOPTS-$*) $(call find-built-pkg-filenames,$*) ; \
	fi
	mkdir -p $(INSTALLEDDIR)
	touch $(INSTALLEDDIR)/$*

# extra layer of indirection so that the config variables can just use 
# 'built-tcl' or similar, not BUILTDIR/tcl
built-%: $(BUILTDIR)/$$*
	

$(BUILTDIR)/%: build-$$*
	@echo "Touching builtfile for $*"
	mkdir -p $(BUILTDIR)
	date > $(BUILTDIR)/$*
	@echo -n "Build of $* completed at "
	@cat $(BUILTDIR)/$*

build-%: $(SPECDIR)/$$*.spec source-$$* $$(addprefix installed-,$$(LOCALBUILDPKGS-$$*))
	@if [ -z "$(RPMBUILDFLAGS-$*)" ]; then \
		echo "building with default rpmbuild flags!" ; \
		rpmbuild $(RPMBUILDFLAGS-DEFAULT) $< ; \
	else \
		rpmbuild $(RPMBUILDFLAGS-$*) $< ; \
	fi

build-deps: $(addprefix build-deps-,$(PKGS))
	

build-deps-%:
	if [ "$(filter-out $(LOCALBUILDDEPS-$*),$(BUILDDEPS-$*))" != "" ]; then \
		echo "Installing build dependencies for $*:" ; \
		echo "  $(filter-out $(LOCALBUILDDEPS-$*),$(BUILDDEPS-$*))" ; \
		sudo yum -y install $(filter-out $(LOCALBUILDDEPS-$*),$(BUILDDEPS-$*)) ; \
	fi

source: $(addprefix source-,$(PKGS))

source-%: $$(addprefix $(SOURCEDIR)/$$*/,$$(filter-out $$(CVSSOURCES-$$*),$$(SOURCES-$$*)))
	

#$(SOURCEDIR)/%: SRC = $(lastword $(subst /, ,%)) PKG = $(firstword $(subst /, ,%))
$(SOURCEDIR)/%:
	# pkg = $(firstword $(subst /, ,$*))
	# src = $(lastword $(subst /, ,$*))
	mkdir -p $(dir $(SOURCEDIR)/$*)
	if [ -z "$(SOURCEFETCHMETHOD-$(firstword $(subst /, ,$*)))" ]; then \
		wget -N -P $(SOURCEDIR) $(if $(SOURCEBASEURL-$(firstword $(subst /, ,$*))),$(SOURCEBASEURL-$(firstword $(subst /, ,$*))),$(SOURCEBASEURL))/$(lastword $(subst /, ,$*)) ; \
	fi
	if [ "$(SOURCEFETCHMETHOD-$(firstword $(subst /, ,$*)))" = "rsync" ]; then \
		rsync -av $(SOURCEBASEURL-$(firstword $(subst /, ,$*)))/$(lastword $(subst /, ,$*)) $(SOURCEDIR)/ ; \
	fi
	@echo "$(SOURCEFETCHMETHOD-$(firstword $(subst /, ,$*)))"
	if [ ! -e $(SOURCEDIR)/$* ]; then \
		ln -s $(SOURCEDIR)/$(lastword $(subst /, ,$*)) $(SOURCEDIR)/$* ; \
	fi

clean: clean-build

clean-source: $(addprefix clean-source-,$(PKGS))
	@echo "Cleaned all sources."

clean-source-%: clean-srcsentinels-%
	@echo "Cleaning sources for $*"
ifneq ($$(SOURCES-$$*),)
	rm -f $(addprefix $(SOURCEDIR)/,$(filter-out $(CVSSOURCES-$*),$(SOURCES-$*)))
endif

clean-srcsentinels: $(addprefix clean-srcsentinels-,$(PKGS))
	@echo "Cleaned all source sentinels."

clean-srcsentinels-%:
	@echo "Cleaning source sentinels for $*"
	rm -rf $(SOURCEDIR)/$*

clean-build: $(addprefix clean-build-,$(PKGS))

clean-build-%:
	rm -f $(BUILTDIR)/$*

SECONDARYSOURCES = $(addprefix $(SOURCEDIR)/,$(foreach pkg,$(PKGS),$(addprefix $(pkg)/,$(filter-out $(CVSSOURCES-$(pkg)),$(SOURCES-$(pkg))))))

# have to get the built files for the locally built deps that were not in PKGS
SECONDARYSOURCES += $(addprefix $(BUILTDIR)/,$(foreach pkg,$(PKGS),$(addprefix $(pkg)/,$(LOCALBUILDPKGS-$(pkg)))))

#
# Ugh, have to prevent automatic deletions of these :-)
#
.SECONDARIES: $(addprefix $(BUILTDIR)/,$(PKGS)) $(addprefix $(INSTALLEDDIR)/,$(PKGS)) $(SECONDARYSOURCES)

# Get rid of a bunch of nasty built-in implicit rules.
.SUFFIXES:

.PHONY: clean clean-srcsentinels clean-source clean-build source all 

