#!/bin/sh
#
# This be captured.
#

env IPMI_PASSWORD=`cat /usr/testbed/etc/ipmi.pswd` \
/usr/testbed/sbin/capture -L -T 15 -r -M ed1 /usr/local/bin/ipmitool -H ed1-mng -C 3 -I lanplus -U ADMIN -E sol activate

#
# XXX Arduino will reset if we screw around with DTR (and RTS?),
# so lock anything flow control related down, or basically anything that
# might cause a USB parameter change.
#
# XXX Also do not try to do anything with the port (e.g., stty) before this,
# because it will open/close the port which will cause the change we are
# trying to avoid.
#
stty -f /dev/cuaU0.init -hupcl -ixon -ixoff -ixany -crtscts
stty -f /dev/cuaU0.lock hupcl ixon ixoff ixany crtscts

## XXX debugging
#echo "Everything locked, cuaU0:"
#stty -g -f /dev/cuaU0
#echo "About to start capture"

/usr/testbed/sbin/capture -y 2 -T 15 -r -s 9600 powduino cuaU0 >/dev/null 2>&1 &

## XXX debugging
#echo "Capture started, cuaU0:"
#stty -g -f /dev/cuaU0

exit 0
