#!/bin/sh

# Never run if systemd is running; it will do this.
[ -f /bin/systemctl ] && /bin/systemctl show-environment >/dev/null 2>&1 \
    && (touch /etc/service/pubsubd/down ; exit 0)

if [ -f /etc/init.d/pubsubd ]; then
    exec /etc/init.d/pubsubd stop
else
    touch /etc/service/pubsubd/down
fi

exit 0
