<?xml version="1.0" encoding="UTF-8"?>
<!--
  
  EMULAB-COPYRIGHT
  Copyright (c) 2005-2007 University of Utah and the Flux Group.
  All rights reserved.
  
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://emulab.net/resources/vtop/0.2" xmlns:vtop="http://emulab.net/resources/vtop/0.2">
  <xs:element name="top">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="vtop:node"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="vtop:link"/>
        <xs:element ref="vtop:type-limit"/>
      </xs:sequence>
      <xs:attribute name="pid" use="required">
        <xs:annotation>
          <xs:documentation>Project ID</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="eid" use="required">
        <xs:annotation>
          <xs:documentation>Experiment ID</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="gid">
        <xs:annotation>
          <xs:documentation>Group ID (optional)</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="uid">
        <xs:annotation>
          <xs:documentation>User ID owning the experiment (optional)</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="node">
    <xs:annotation>
      <xs:documentation>Nodes in the topology - zero or more</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="vtop:node_type"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="vtop:desire"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="vtop:node_option"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="node_type">
    <xs:annotation>
      <xs:documentation>Types of virtual nodes that this physical node can satisfy</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="type_name" type="xs:string">
          <xs:annotation>
            <xs:documentation>Name of the type - will almost certainly not be unique</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:choice>
          <xs:element ref="vtop:type_slots"/>
          <xs:element ref="vtop:unlimited"/>
        </xs:choice>
        <xs:element minOccurs="0" ref="vtop:static"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="type_slots">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="unlimited">
    <xs:complexType/>
  </xs:element>
  <xs:element name="static">
    <xs:complexType/>
  </xs:element>
  <xs:element name="desire" type="vtop:FeatureSpec"/>
  <xs:element name="node_option">
    <xs:annotation>
      <xs:documentation>Flags for this virtual node</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vtop:option_name"/>
        <xs:element minOccurs="0" ref="vtop:option_value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="option_name">
    <xs:annotation>
      <xs:documentation>Name of the option</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="trivial_bw"/>
        <xs:enumeration value="subnode_of"/>
        <xs:enumeration value="unique"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="option_value" type="xs:string">
    <xs:annotation>
      <xs:documentation>Value for the option - not all options require values</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="link">
    <xs:annotation>
      <xs:documentation>Links in the topology - zero or more</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vtop:source_interface"/>
        <xs:element ref="vtop:destination_interface"/>
        <xs:element ref="vtop:bandwidth"/>
        <xs:element ref="vtop:latency"/>
        <xs:element ref="vtop:packet_loss"/>
        <xs:element maxOccurs="unbounded" ref="vtop:link_type"/>
      </xs:sequence>
      <xs:attribute name="name" use="required">
        <xs:annotation>
          <xs:documentation>Name of the link - must be unique in the top</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="source_interface" type="vtop:InterfaceSpec"/>
  <xs:element name="destination_interface" type="vtop:InterfaceSpec">
    <xs:annotation>
      <xs:documentation>Second interface for this link</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="bandwidth">
    <xs:annotation>
      <xs:documentation>Bandwidth of the link in kbps</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:float">
        <xs:minExclusive value="0.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="latency">
    <xs:annotation>
      <xs:documentation>Latency of the link in ms</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:float">
        <xs:minInclusive value="0.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="packet_loss">
    <xs:simpleType>
      <xs:restriction base="xs:float">
        <xs:minInclusive value="0.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="link_type">
    <xs:annotation>
      <xs:documentation>Type of virtual link this physical link is allowed to satisfy</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="type_name" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="type-limit">
    <xs:complexType>
      <xs:attribute name="node_type" use="required"/>
      <xs:attribute name="limit" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <!--
    These should probably go into a seperate file included by both this file
    and the ptop spec
  -->
  <xs:complexType name="InterfaceSpec">
    <xs:sequence>
      <xs:element ref="vtop:node_name"/>
      <xs:element ref="vtop:interface"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="node_name" type="xs:string">
    <xs:annotation>
      <xs:documentation>Name of the node, which must match one of the nodes in this top</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="interface" type="xs:string">
    <xs:annotation>
      <xs:documentation>Name of the interface itself</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="FeatureSpec">
    <xs:sequence>
      <xs:element ref="vtop:feature_name"/>
      <xs:element ref="vtop:feature_penalty"/>
      <xs:element minOccurs="0" ref="vtop:violatable"/>
      <xs:choice minOccurs="0">
        <xs:annotation>
          <xs:documentation>Flags for special types of operators</xs:documentation>
        </xs:annotation>
        <xs:sequence>
          <xs:element ref="vtop:global"/>
          <xs:element name="operator">
            <xs:simpleType>
              <xs:restriction base="xs:token">
                <xs:enumeration value="OnceOnly"/>
                <xs:enumeration value="FirstFree"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
        <xs:sequence>
          <xs:element ref="vtop:local"/>
          <xs:element name="operator">
            <xs:simpleType>
              <xs:restriction base="xs:token">
                <xs:enumeration value="+"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="feature_name" type="xs:string">
    <xs:annotation>
      <xs:documentation>Name of this feature</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="feature_penalty">
    <xs:annotation>
      <xs:documentation>The penalty associated with this feature</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:float">
        <xs:minInclusive value="0.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="violatable">
    <xs:annotation>
      <xs:documentation>If this flag is present, not having the feature is considered a violation</xs:documentation>
    </xs:annotation>
    <xs:complexType/>
  </xs:element>
  <xs:element name="global">
    <xs:complexType/>
  </xs:element>
  <xs:element name="local">
    <xs:complexType/>
  </xs:element>
</xs:schema>
