[main]
#dhcp=internal
#dhcp=dhclient

#
# We decide the system's fate via our udev rules.
#
no-auto-default=*

#
# We want to set the hostname to the per-expt FQDN.
#
hostname-mode=none

#
# Some systems (Ubuntu) disallow keyfile from managing
# many devices (e.g. in preference to legacy ifupdown).
# We can't have that, so override.
#
[keyfile]
unmanaged-devices=
