#!/usr/bin/expect

## For debugging
#exp_internal 1

spawn /usr/local/sbin/console-nossl -l powduino
set timeout 5
expect {
    timeout {
	send_error "powduino capture unresponsive or busy.\n"
	exit 1
    }
    eof {
	send_error "powduino capture disconnected.\n"
	exit 1
    }
    "Connected to localhost\."
}
send "\r"
expect {
    timeout {
	send_error "powduino unresponsive.\n"
	exit 1
    }
    eof {
	send_error "powduino terminated.\n"
	exit 1
    }
    -re {.*power> }
}
send "temp\r"
expect {
    timeout {
	send_error "powduino unresponsive.\n"
	exit 1
    }
    eof {
	send_error "powduino terminated.\n"
	exit 1
    }
    -re {\n([0-9]+\.[0-9]+).*power> } {
	send_user -- $expect_out(1,string)
    }
    "Invalid command" {
	send "temp\r"
	exp_continue -continue_timer
    }
}
exit 0
