#!/usr/bin/env python

#
# This script manages Benetel O-RU devices. It does not (and should
# not grow) any testbed-specific dependencies, so that it may be used
# on any system that runs Python and has SSH binaries in the path.
#
# This script is able to perform various operations on Benetel RU devices:
#
# * Configuration management
#     - Reset all managed configuration values to defaults
#     - Update specific configuration settings
#     - Get (all) current configuration settings
#
# * Device status
#     - Check device up/down status (ping)
#     - Check radio initialization status
#     - Wait for radio initialization to complete
#     - Get firmware version
#
# Note: Power control and reboot are handled by the standard testbed
#       `node_reboot` and `power` scripts. Modules specifically for
#       handling Benetel RUs should be present in these scripts. They use
#       this script to check device status and wait for initialization
#       to complete. Reboot should NEVER be run directly on the device
#       via remote shell. Doing so risks damage if a corresponding DU
#       is sending samples before initialization is complete (yes,
#       this is insane, but true).
#

import sys
import time
import logging
import re
import json
from argparse import ArgumentParser
from getpass import getpass
from libdevproxy import Utilities, DeviceConfig, DeviceWrapper

##############################################################################
#
# BenetelConfig class definition
#
class BenetelConfig(DeviceConfig):
    DEFAULT_SETTINGS = {
        'center_frequency': {
            'def': 3370.2,
            'allowed_ranges': ((3358.0,3800.0),)
        },
        'bandwidth': {
            'def': 20.0,
            'allowed_values': (20.0, 40.0, 60.0, 80.0, 100.0)
        },
        'gain': {
            'def': 37.0,
            'allowed_ranges': ((1.0,37.0),)
        },
        'fh_cplane_vlan': {
            'def': 1,
            'allowed_ranges': ((1,4096),)
        },
        'fh_uplane_vlan': {
            'def': 1,
            'allowed_ranges': ((1,4096),)
        },
        'du_cplane_mac': {
            'def': '000000000000',
            'allowed_patterns': (r'[0-9A-Fa-f]{12}',)
        },
        'du_uplane_mac': {
            'def': '000000000000',
            'allowed_patterns': (r'[0-9A-Fa-f]{12}',)
        },
        'mimo_mode': {
            'def': '2_4',
            'allowed_values': ('1_3','2_4','1_2_3_4_4x2','1_2_3_4_4x4')
        },
        'downlink_scaling': {
            'def': 0,
            'allowed_values': (0, 6, 12, 18)
        },
        'prach_format': {
            'def': 'short',
            'allowed_values': ('short', 'long')
        },
        'compression': {
            'def': 'dynamic_compressed',
            'allowed_values': ('static_uncompressed', 'static_compressed',
                               'dynamic_uncompressed', 'dynamic_compressed')
        },
        'lf_prach_compression_enable': {
            'def': 'false',
            'allowed_values': ('true', 'false')
        },
        'flexran_prach_workaround': {
            'def': 'disabled',
            'allowed_values': ('enabled', 'disabled')
        },
# TDD setting needs special attention...
#        'TDD_mode': {
#            'def': 'DDDDDDDSUU',
#            'allowed_values': ('DDDDDDDSUU', 'DDDSUUDDDD', 'DDDSUUDSUU',
#                               'DDSUUUDSUU', 'DDDSU')
#        }
    }

##############################################################################
#
# BenetelWrapper class definition
#
class BenetelWrapper(DeviceWrapper):
    DEF_LOG_LEVEL = logging.INFO
    DEF_USER = "root"
    DEF_PASSWD = ""
    DEF_PING_TIMEOUT = 5
    DEF_BOOT_TIMEOUT = 120
    DEF_SHUTDOWN_TIME = 30
    DEF_RADIO_ONLINE_TIMEOUT = 300
    WAIT_LOG_SLEEP = 1
    FW_VERSION_UNKNOWN = {'major':'X', 'minor':'Y', 'revision':'Z'}
    FW_VERSION_FILE = "/etc/benetel-rootfs-version"
    RADIO_BOOT_LOG = "/tmp/logs/radio_status"
    RADIO_ONLINE_STATUS_PATTERN = r'^\[INFO\] Radio bringup complete'
    RADIO_SETUP_SCRIPT = "/usr/sbin/radio_setup_a.sh"
    RADIO_SETUP_SCRIPT_PATTERN = r'-w (C[0-9A-Fa-f]+) -x 0x([0-9A-Fa-f]+)'
    RADIO_CONFIG_FILE = "/etc/ru_config.cfg"
    RADIO_CONFIG_FILE_PATTERN = r'^\s*(\w+)\s*=\s*([.:\w]+)'
    SINGLE_FILE_SETTINGS_MAP = {
        'center_frequency': '/etc/ru-center-frequency-mhz',
        'bandwidth': '/etc/ru-bandwidth',
        'gain': '/etc/ru-tx-gain-db',
    }
    RADIO_SETUP_SCRIPT_SETTINGS = \
        ('fh_cplane_vlan', 'fh_uplane_vlan', 'du_cplane_mac',
         'du_uplane_mac')
    RADIO_CONFIG_FILE_MAP = {
        'mimo_mode': 'mimo_mode',
        'downlink_scaling': 'downlink_scaling',
        'prach_format': 'prach_format',
        'compression': 'compression',
        'lf_prach_compression_enable': 'lf_prach_compression_enable',
        'flexran_prach_workaround': 'flexran_prach_workaround',
        'bandwidth_hz': 'bandwidth',
        'centre_frequency_hz': 'center_frequency',
        'tx_power_dbm': 'gain',
        'c_plane_du_mac': 'du_cplane_mac',
        'u_plane_du_mac': 'du_uplane_mac',
        'c_plane_du_vlan': 'fh_cplane_vlan',
        'u_plane_du_vlan_downlink': 'fh_uplane_vlan',
        'u_plane_du_vlan_uplink': 'fh_uplane_vlan'
    }

    def __init__(self, mgmt_addr, username=DEF_USER, keyfile=None,
                 log_level = DEF_LOG_LEVEL):
        super().__init__(mgmt_addr, username, keyfile, log_level)

    def connect_session(self, password = DEF_PASSWD, retries = 0,
                        ping_timeout = DEF_PING_TIMEOUT):
        super().connect_session(password, retries, ping_timeout)
        self._parse_fwversion(self._fwversion)

    def _parse_fwversion(self, fwstr):
        hw, version, *other = fwstr.split("-")
        major, minor, rev = version.split(".")
        major = major.split("v")[1]
        self._hardware = hw
        self._fwversion = { 'major': int(major), 'minor': int(minor),
                            'revision': int(rev) }

    def get_firmware_string(self):
        return ".".join([str(self._fwversion[x]) for x in
                         ("major", "minor", "revision")])

    def wait_for_radio_online(self, timeout = DEF_RADIO_ONLINE_TIMEOUT):
        res = []
        stime = time.time()
        self.wait_for_ping(self.DEF_BOOT_TIMEOUT)
        self.lgr.info("Device pings. Waiting for radio.")
        while time.time() <= stime + timeout:
            try:
                res = self.get_session().grep_remote_file(
                    self.RADIO_BOOT_LOG,
                    self.RADIO_ONLINE_STATUS_PATTERN,
                    timeout = timeout)
            except FileNotFoundError:
                time.sleep(self.WAIT_LOG_SLEEP)
            else:
                break
        if len(res) > 0:
            self.lgr.info("Radio is ready.")
            return True
        return False

    def _fetch_single_file_setting(self, setting):
        rfile = self.SINGLE_FILE_SETTINGS_MAP[setting]
        value = self.get_session().read_remote_file(rfile)[0].strip()
        if setting in ("bandwidth",):
            value = float(value) / 1e6 # Convert to MHz for these.
        return value

    def _push_single_file_setting(self, setting, value):
        rfile = self.SINGLE_FILE_SETTINGS_MAP[setting]
        if setting in ("bandwidth",):
            value *= 1e6  # Convert to Hz for these settings.
        outlines = (str(value),)
        self.get_session().write_remote_file(rfile, outlines, overwrite=True)

    def _fetch_radio_setup_script_settings(self):
        settings = {}
        scrset = {}
        for ln in self.get_session().read_remote_file(self.RADIO_SETUP_SCRIPT):
            m = re.search(self.RADIO_SETUP_SCRIPT_PATTERN, ln)
            if m:
                scrset[m[1]] = m[2]
        settings['fh_cplane_vlan'] = int(scrset['C0331'], base=16)
        settings['fh_uplane_vlan'] = int(scrset['C0318'], base=16)
        settings['du_cplane_mac'] = scrset['C031A'] + scrset['C0319']
        settings['du_uplane_mac'] = scrset['C0316'] + scrset['C0315']
        return settings

    def _push_radio_setup_script_settings(self, settings):
        outlines = []
        prepat = r'-w \1 -x 0x'
        subst = {
            'C0331': prepat +
            format(settings['fh_cplane_vlan'], 'X'),
            'C0318': prepat +
            format(settings['fh_uplane_vlan'], 'X'),
            'C0330': prepat +
            format(settings['fh_uplane_vlan'], 'X'),
            'C031A': prepat +
            settings['du_cplane_mac'][0:4].upper(),
            'C0319': prepat +
            settings['du_cplane_mac'][4:].upper(),
            'C0316': prepat +
            settings['du_uplane_mac'][0:4].upper(),
            'C0315': prepat +
            settings['du_uplane_mac'][4:].upper(),
        }
        for ln in self.get_session().read_remote_file(self.RADIO_SETUP_SCRIPT):
            ln = ln.rstrip()
            m = re.search(self.RADIO_SETUP_SCRIPT_PATTERN, ln)
            if m and m[1] in subst:
                res = re.sub(self.RADIO_SETUP_SCRIPT_PATTERN, subst[m[1]], ln)
                outlines.append(res)
            else:
                outlines.append(ln)
        outlines.append("") # Add final newline...
        self.get_session().\
            write_remote_file(self.RADIO_SETUP_SCRIPT, outlines, overwrite=True)

    def _fetch_radio_config_file_settings(self):
        settings = {}
        mapkeys = self.RADIO_CONFIG_FILE_MAP.keys()
        for ln in self.get_session().read_remote_file(self.RADIO_CONFIG_FILE):
            m = re.search(self.RADIO_CONFIG_FILE_PATTERN, ln)
            if m and m[1] in mapkeys:
                key, val = m[1], m[2]
                if key in ("centre_frequency_hz", "bandwidth_hz"):
                    val = float(val) / 1e6  # We handle these settings in MHz.
                elif key in ("c_plane_du_vlan", "u_plane_du_vlan_downlink",
                             "u_plane_du_vlan_downlink"):
                    val = int(val, base = 16) # Benetel keeps these in hex...
                elif key in ("c_plane_du_mac", "u_plane_du_mac"):
                    val = val.replace(":", "") # Emulab convention.
                settings[self.RADIO_CONFIG_FILE_MAP[key]] = val
        return settings

    def _push_radio_config_file_settings(self, settings):
        outlines = []
        mapkeys = self.RADIO_CONFIG_FILE_MAP.keys()
        for ln in self.get_session().read_remote_file(self.RADIO_CONFIG_FILE):
            ln = ln.rstrip()
            m = re.search(self.RADIO_CONFIG_FILE_PATTERN, ln)
            if m and m[1] in mapkeys:
                key = m[1]
                val = settings[self.RADIO_CONFIG_FILE_MAP[key]]
                if key in ("centre_frequency_hz", "bandwidth_hz"):
                    val = int(val*1e6)  # Convert these to Hz and round to int
                elif key in ("c_plane_du_vlan", "u_plane_du_vlan_downlink",
                             "u_plane_du_vlan_uplink"):
                    val = format(val, "x")  # Convert to hex for Benetel...
                elif key in ("c_plane_du_mac", "u_plane_du_mac"):
                    val = ":".join(re.findall("..", val)) # "Normal" mac string
                outlines.append(re.sub(self.RADIO_CONFIG_FILE_PATTERN,
                                       r'\1=' + str(val), ln))
            else:
                outlines.append(ln)
        outlines.append("") # Add final newline since this is a script...
        self.get_session().\
            write_remote_file(self.RADIO_CONFIG_FILE, outlines, overwrite=True)

    def fetch_settings(self):
        settings = BenetelConfig()
        if self._fwversion['major'] == 0 \
           or self._fwversion['major'] == 1 and self._fwversion['minor'] < 4:
            for stg in self.SINGLE_FILE_SETTINGS_MAP.keys():
                settings[stg] = self._fetch_single_file_setting(stg)
            settings.update(self._fetch_radio_setup_script_settings())
        settings.update(self._fetch_radio_config_file_settings())
        return settings

    def push_settings(self, settings):
        if not type(settings) == BenetelConfig:
            raise ValueError(f"{Utilities.whoami(self)}: 'settings' argument "
                             "must be a BenetelConfig object!")
        if self._fwversion['major'] == 0 \
           or self._fwversion['major'] == 1 and self._fwversion['minor'] < 4:
            for stg in self.SINGLE_FILE_SETTINGS_MAP.keys():
                self._push_single_file_setting(stg, settings[stg])
            self._push_radio_setup_script_settings(settings)
        self._push_radio_config_file_settings(settings)

##############################################################################
#
# Top-level code (main script entry point and helpers)
#
def connect(args, loglvl):
    bw = BenetelWrapper(args.address, args.username, log_level = loglvl)
    passwd = ""
    if args.read_password:
        passwd = getpass()
    elif args.password:
        passwd = args.password
    bw.connect_session(password=passwd, ping_timeout=args.ping_timeout)
    passwd = None
    return bw

def update_config(args, bw):
    cfg = []
    json_data = None
    if args.json_config == "-":
        json_data = sys.stdin.read()
    else:
        with open(args.json_config, "r") as cfg_f:
            json_data = cfg_f.read()
    cfg = json.loads(json_data)
    dcfg = bw.fetch_settings()
    dcfg.update(cfg)
    bw.push_settings(dcfg)

def parse_args():
    parser = ArgumentParser()
    parser.add_argument("address", help="Address (hostname or IP) of the device.")
    parser.add_argument("-u", "--username", default=BenetelWrapper.DEF_USER,
                        help="Username to supply when logging in to device.")
    parser.add_argument("-R", "--read-password", action="store_true",
                        help="Read password from command line. "
                        "Note: This argument overrides the `password` argument")
    parser.add_argument("-p", "--password", help="Password for authenticating.")
    parser.add_argument("-g", "--get-config", action="store_true",
                        help="Get configuration from device and print to "
                        "stdout in JSON format.")
    parser.add_argument("-j", "--json-config", help="Apply configuration, "
                        "specified in a JSON file, to the device "
                        "(specify '-' to read config from stdin). "
                        "Does NOT imply the `reboot` argument.")
    parser.add_argument("-P", "--ping-timeout", type=int,
                        default=BenetelWrapper.DEF_PING_TIMEOUT,
                        help="Number of seconds to wait for the device to "
                        "respond to pings when connecting initially before "
                        "timing out.")
    parser.add_argument("-q", "--quiet", action="store_true",
                        help="Quiet operation. Do not print informational "
                        "messages.")
    parser.add_argument("-r", "--reboot", action="store_true",
                        help="Reboot the RU (via `reboot` over SSH session). "
                        "Performed after most other actions "
                        "(see `--wait` argument).")
    parser.add_argument("-w", "--wait", type=int, default=-1,
                        help="Wait for the radio on the device to become "
                        "active, timing out after WAIT seconds. Does NOT imply "
                        "the `reboot` argument. This action is performed last "
                        "(after all other actions complete).")
    return parser.parse_args()
   
def main():
    args = parse_args()
    loglvl = logging.ERROR if args.quiet else logging.INFO
    lgr = Utilities.mk_logger("beneshell", loglvl)
    bw = None
    try:
        bw = connect(args, loglvl)
        if not args.get_config:
            lgr.info(f"Connected to {args.address}. Firmware: {bw.get_firmware_string()}")
    except:
        lgr.exception("Failed to connect to the device:")
        return 1
    if args.json_config:
        try:
            update_config(args, bw)
        except:
            lgr.exception("Failed to update configuration on device:")
            return 1
        else:
            lgr.info("Device settings updated successfully.")
    if args.get_config:
        try:
            dcfg = bw.fetch_settings()
            print(json.dumps(dict(dcfg), sort_keys=True, indent=4))
        except:
            lgr.exception("Failed to fetch or print device configuration:")
            return 1
    if args.reboot:
        lgr.info("Rebooting device.")
        try:
            bw.reboot()
        except:
            lgr.exception("Failure encountered while trying to reboot device:")
            return 1
    if args.wait >= 0:
        res = False
        try:
            res = bw.wait_for_radio_online(args.wait)
        except:
            lgr.exception("Failed while waiting for radio to come online:")
            return 1
        if not res:
            lgr.warning("Timed out while waiting for radio to come online.")
            return 1
    return 0

if __name__ == "__main__":
    sys.exit(main())
