#!/bin/sh

# Never run if systemd is running; it will do this.
[ -f /bin/systemctl ] && /bin/systemctl show-environment >/dev/null 2>&1 \
    && (touch /etc/service/testbed/down ; exit 0)

if [ -f /usr/local/etc/emulab/initscripts/testbed ]; then
    exec /usr/local/etc/emulab/initscripts/testbed stop
fi

exit 0
